# Auto generated by pyminer2 extension develop tools

from pmsetuptools.extbase import BaseExtension

class MyExtension(BaseExtension):
    def on_load(self):
        self._my_toolbar = self.widgets["MyToolbar"]

        self.MyDockWindow = self.widget_classes["MyDockWindow"]


    def on_install(self):
        pass

    def on_uninstall(self):
        pass

from PyQt5.QtWidgets import QWidget

class MyDockWindow(QWidget):
        pass
