# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(647, 509)
        self.horizontalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.dockWidget = QtWidgets.QDockWidget(Form)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QPushButton('aaaaaaaaaa')
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dockWidget.setWidget(self.dockWidgetContents)

        self.horizontalLayout.addWidget(self.dockWidget)

        self.dockWidget_2 = QtWidgets.QDockWidget(Form)
        self.dockWidget_2.setObjectName("dockWidget_2")

        self.dockWidgetContents_4 = QtWidgets.QTextEdit()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")

        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.pushButton.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.dockWidget_2.setWidget(self.dockWidgetContents_4)

        self.horizontalLayout.addWidget(self.dockWidget_2)

        self.dockWidget_3 = QtWidgets.QDockWidget(Form)

        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_5 = QtWidgets.QTextEdit()
        self.dockWidgetContents_5.setText('hhhhhhhhhhhhhhhhh')
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")

        self.dockWidget_3.setWidget(self.dockWidgetContents_5)

        self.horizontalLayout.addWidget(self.dockWidget_3)

        self.dockWidget_4 = QtWidgets.QDockWidget(Form)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_7 = QtWidgets.QTextEdit()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.dockWidget_4.setWidget(self.dockWidgetContents_7)

        self.horizontalLayout.addWidget(self.dockWidget_4)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.setDockNestingEnabled(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton.setText(_translate("Form", "PushButton"))


class MainWindow(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self, parent=None):
        super(QtWidgets.QMainWindow, self).__init__()
        self.setupUi(self)


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    uf = MainWindow()
    uf.show()
    app.exec()
    print(123123)

