# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget_var = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_var.setObjectName("listWidget_var")
        self.verticalLayout_2.addWidget(self.listWidget_var)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_to_right = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_to_right.setObjectName("pushButton_to_right")
        self.verticalLayout_4.addWidget(self.pushButton_to_right)
        self.pushButton_to_right_all = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_to_right_all.setObjectName("pushButton_to_right_all")
        self.verticalLayout_4.addWidget(self.pushButton_to_right_all)
        self.verticalLayout_17.addLayout(self.verticalLayout_4)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_to_left = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_to_left.setObjectName("pushButton_to_left")
        self.verticalLayout_16.addWidget(self.pushButton_to_left)
        self.pushButton_to_left_all = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_to_left_all.setObjectName("pushButton_to_left_all")
        self.verticalLayout_16.addWidget(self.pushButton_to_left_all)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.listWidget_selecetd = QtWidgets.QListWidget(self.tab)
        self.listWidget_selecetd.setObjectName("listWidget_selecetd")
        self.verticalLayout_3.addWidget(self.listWidget_selecetd)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.listWidget_group = QtWidgets.QListWidget(self.tab)
        self.listWidget_group.setObjectName("listWidget_group")
        self.verticalLayout_3.addWidget(self.listWidget_group)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_cnt_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_cnt_2.setObjectName("checkBox_cnt_2")
        self.verticalLayout_9.addWidget(self.checkBox_cnt_2)
        self.checkBox_valid_cnt_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_valid_cnt_2.setObjectName("checkBox_valid_cnt_2")
        self.verticalLayout_9.addWidget(self.checkBox_valid_cnt_2)
        self.checkBox_miss_cnt_3 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_miss_cnt_3.setObjectName("checkBox_miss_cnt_3")
        self.verticalLayout_9.addWidget(self.checkBox_miss_cnt_3)
        self.checkBox_miss_cnt_4 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_miss_cnt_4.setObjectName("checkBox_miss_cnt_4")
        self.verticalLayout_9.addWidget(self.checkBox_miss_cnt_4)
        self.checkBox_cov_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_cov_5.setObjectName("checkBox_cov_5")
        self.verticalLayout_9.addWidget(self.checkBox_cov_5)
        self.checkBox_cov_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_cov_6.setObjectName("checkBox_cov_6")
        self.verticalLayout_9.addWidget(self.checkBox_cov_6)
        self.checkBox_max_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_max_2.setObjectName("checkBox_max_2")
        self.verticalLayout_9.addWidget(self.checkBox_max_2)
        self.checkBox_min_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_min_2.setObjectName("checkBox_min_2")
        self.verticalLayout_9.addWidget(self.checkBox_min_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_sum_5 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_sum_5.setObjectName("checkBox_sum_5")
        self.verticalLayout_10.addWidget(self.checkBox_sum_5)
        self.checkBox_mean_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_mean_2.setObjectName("checkBox_mean_2")
        self.verticalLayout_10.addWidget(self.checkBox_mean_2)
        self.checkBox_median_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_median_2.setObjectName("checkBox_median_2")
        self.verticalLayout_10.addWidget(self.checkBox_median_2)
        self.checkBox_mode_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_mode_2.setObjectName("checkBox_mode_2")
        self.verticalLayout_10.addWidget(self.checkBox_mode_2)
        self.checkBox_sum_6 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_sum_6.setObjectName("checkBox_sum_6")
        self.verticalLayout_10.addWidget(self.checkBox_sum_6)
        self.checkBox_sum_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_sum_7.setObjectName("checkBox_sum_7")
        self.verticalLayout_10.addWidget(self.checkBox_sum_7)
        self.checkBox_var_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_var_2.setObjectName("checkBox_var_2")
        self.verticalLayout_10.addWidget(self.checkBox_var_2)
        self.checkBox_std_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_std_2.setObjectName("checkBox_std_2")
        self.verticalLayout_10.addWidget(self.checkBox_std_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_q1_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_q1_2.setObjectName("checkBox_q1_2")
        self.verticalLayout_11.addWidget(self.checkBox_q1_2)
        self.checkBox_q3_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_q3_2.setObjectName("checkBox_q3_2")
        self.verticalLayout_11.addWidget(self.checkBox_q3_2)
        self.checkBox_qrange_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_qrange_2.setObjectName("checkBox_qrange_2")
        self.verticalLayout_11.addWidget(self.checkBox_qrange_2)
        self.checkBox_cov_7 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_cov_7.setObjectName("checkBox_cov_7")
        self.verticalLayout_11.addWidget(self.checkBox_cov_7)
        self.checkBox_range_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_range_2.setObjectName("checkBox_range_2")
        self.verticalLayout_11.addWidget(self.checkBox_range_2)
        self.checkBox_sum_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_sum_8.setObjectName("checkBox_sum_8")
        self.verticalLayout_11.addWidget(self.checkBox_sum_8)
        self.checkBox_cov_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_cov_8.setObjectName("checkBox_cov_8")
        self.verticalLayout_11.addWidget(self.checkBox_cov_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 277, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.checkBoxhist = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxhist.setObjectName("checkBoxhist")
        self.verticalLayout_14.addWidget(self.checkBoxhist)
        self.checkBox_normal = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_normal.setObjectName("checkBox_normal")
        self.verticalLayout_14.addWidget(self.checkBox_normal)
        self.checkBox_value = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_value.setObjectName("checkBox_value")
        self.verticalLayout_14.addWidget(self.checkBox_value)
        self.checkBox_boxplot = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_boxplot.setObjectName("checkBox_boxplot")
        self.verticalLayout_14.addWidget(self.checkBox_boxplot)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_13.addWidget(self.tabWidget)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_help = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout_3.addWidget(self.pushButton_help)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_ok = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_13.addWidget(self.widget_3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "显示描述性统计量"))
        self.label_3.setText(_translate("Form", "全部变量:"))
        self.pushButton_to_right.setText(_translate("Form", "<<"))
        self.pushButton_to_right_all.setText(_translate("Form", ">>"))
        self.pushButton_to_left.setText(_translate("Form", ">>"))
        self.pushButton_to_left_all.setText(_translate("Form", "<<"))
        self.label.setText(_translate("Form", "已选变量:"))
        self.label_2.setText(_translate("Form", "分组变量:(可选)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "基本"))
        self.checkBox_cnt_2.setText(_translate("Form", "计数"))
        self.checkBox_valid_cnt_2.setText(_translate("Form", "非缺失值计数"))
        self.checkBox_miss_cnt_3.setText(_translate("Form", "缺失值计数"))
        self.checkBox_miss_cnt_4.setText(_translate("Form", "缺失值占比"))
        self.checkBox_cov_5.setText(_translate("Form", "唯一值"))
        self.checkBox_cov_6.setText(_translate("Form", "唯一占比"))
        self.checkBox_max_2.setText(_translate("Form", "最大值"))
        self.checkBox_min_2.setText(_translate("Form", "最小值"))
        self.checkBox_sum_5.setText(_translate("Form", "总和"))
        self.checkBox_mean_2.setText(_translate("Form", "均值"))
        self.checkBox_median_2.setText(_translate("Form", "中位数"))
        self.checkBox_mode_2.setText(_translate("Form", "众数"))
        self.checkBox_sum_6.setText(_translate("Form", "峰度"))
        self.checkBox_sum_7.setText(_translate("Form", "偏度"))
        self.checkBox_var_2.setText(_translate("Form", "方差"))
        self.checkBox_std_2.setText(_translate("Form", "标准差"))
        self.checkBox_q1_2.setText(_translate("Form", "下四分位数Q1"))
        self.checkBox_q3_2.setText(_translate("Form", "上四分位数Q3"))
        self.checkBox_qrange_2.setText(_translate("Form", "四分位间距"))
        self.checkBox_cov_7.setText(_translate("Form", "变异系数"))
        self.checkBox_range_2.setText(_translate("Form", "极差"))
        self.checkBox_sum_8.setText(_translate("Form", "平方和"))
        self.checkBox_cov_8.setText(_translate("Form", "均值标准误"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "选项"))
        self.checkBoxhist.setText(_translate("Form", "数据直方图"))
        self.checkBox_normal.setText(_translate("Form", "带正态曲线的数据直方图"))
        self.checkBox_value.setText(_translate("Form", "单值图"))
        self.checkBox_boxplot.setText(_translate("Form", "数据箱线图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "图形"))
        self.pushButton_help.setText(_translate("Form", "帮助"))
        self.pushButton_ok.setText(_translate("Form", "确定"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
