# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat_index.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_cnt = QtWidgets.QCheckBox(Form)
        self.checkBox_cnt.setObjectName("checkBox_cnt")
        self.verticalLayout_2.addWidget(self.checkBox_cnt)
        self.checkBox_valid_cnt = QtWidgets.QCheckBox(Form)
        self.checkBox_valid_cnt.setObjectName("checkBox_valid_cnt")
        self.verticalLayout_2.addWidget(self.checkBox_valid_cnt)
        self.checkBox_miss_cnt = QtWidgets.QCheckBox(Form)
        self.checkBox_miss_cnt.setObjectName("checkBox_miss_cnt")
        self.verticalLayout_2.addWidget(self.checkBox_miss_cnt)
        self.checkBox_miss_cnt_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_miss_cnt_2.setObjectName("checkBox_miss_cnt_2")
        self.verticalLayout_2.addWidget(self.checkBox_miss_cnt_2)
        self.checkBox_cov_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_cov_3.setObjectName("checkBox_cov_3")
        self.verticalLayout_2.addWidget(self.checkBox_cov_3)
        self.checkBox_cov_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_cov_4.setObjectName("checkBox_cov_4")
        self.verticalLayout_2.addWidget(self.checkBox_cov_4)
        self.checkBox_max = QtWidgets.QCheckBox(Form)
        self.checkBox_max.setObjectName("checkBox_max")
        self.verticalLayout_2.addWidget(self.checkBox_max)
        self.checkBox_min = QtWidgets.QCheckBox(Form)
        self.checkBox_min.setObjectName("checkBox_min")
        self.verticalLayout_2.addWidget(self.checkBox_min)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_sum = QtWidgets.QCheckBox(Form)
        self.checkBox_sum.setObjectName("checkBox_sum")
        self.verticalLayout_3.addWidget(self.checkBox_sum)
        self.checkBox_mean = QtWidgets.QCheckBox(Form)
        self.checkBox_mean.setObjectName("checkBox_mean")
        self.verticalLayout_3.addWidget(self.checkBox_mean)
        self.checkBox_median = QtWidgets.QCheckBox(Form)
        self.checkBox_median.setObjectName("checkBox_median")
        self.verticalLayout_3.addWidget(self.checkBox_median)
        self.checkBox_mode = QtWidgets.QCheckBox(Form)
        self.checkBox_mode.setObjectName("checkBox_mode")
        self.verticalLayout_3.addWidget(self.checkBox_mode)
        self.checkBox_sum_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_sum_2.setObjectName("checkBox_sum_2")
        self.verticalLayout_3.addWidget(self.checkBox_sum_2)
        self.checkBox_sum_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_sum_3.setObjectName("checkBox_sum_3")
        self.verticalLayout_3.addWidget(self.checkBox_sum_3)
        self.checkBox_var = QtWidgets.QCheckBox(Form)
        self.checkBox_var.setObjectName("checkBox_var")
        self.verticalLayout_3.addWidget(self.checkBox_var)
        self.checkBox_std = QtWidgets.QCheckBox(Form)
        self.checkBox_std.setObjectName("checkBox_std")
        self.verticalLayout_3.addWidget(self.checkBox_std)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_q1 = QtWidgets.QCheckBox(Form)
        self.checkBox_q1.setObjectName("checkBox_q1")
        self.verticalLayout.addWidget(self.checkBox_q1)
        self.checkBox_q3 = QtWidgets.QCheckBox(Form)
        self.checkBox_q3.setObjectName("checkBox_q3")
        self.verticalLayout.addWidget(self.checkBox_q3)
        self.checkBox_qrange = QtWidgets.QCheckBox(Form)
        self.checkBox_qrange.setObjectName("checkBox_qrange")
        self.verticalLayout.addWidget(self.checkBox_qrange)
        self.checkBox_cov = QtWidgets.QCheckBox(Form)
        self.checkBox_cov.setObjectName("checkBox_cov")
        self.verticalLayout.addWidget(self.checkBox_cov)
        self.checkBox_range = QtWidgets.QCheckBox(Form)
        self.checkBox_range.setObjectName("checkBox_range")
        self.verticalLayout.addWidget(self.checkBox_range)
        self.checkBox_sum_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_sum_4.setObjectName("checkBox_sum_4")
        self.verticalLayout.addWidget(self.checkBox_sum_4)
        self.checkBox_cov_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_cov_2.setObjectName("checkBox_cov_2")
        self.verticalLayout.addWidget(self.checkBox_cov_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok_2 = QtWidgets.QPushButton(Form)
        self.pushButton_ok_2.setObjectName("pushButton_ok_2")
        self.horizontalLayout.addWidget(self.pushButton_ok_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "显示描述性统计量"))
        self.checkBox_cnt.setText(_translate("Form", "计数"))
        self.checkBox_valid_cnt.setText(_translate("Form", "非缺失值计数"))
        self.checkBox_miss_cnt.setText(_translate("Form", "缺失值计数"))
        self.checkBox_miss_cnt_2.setText(_translate("Form", "缺失值占比"))
        self.checkBox_cov_3.setText(_translate("Form", "唯一值"))
        self.checkBox_cov_4.setText(_translate("Form", "唯一占比"))
        self.checkBox_max.setText(_translate("Form", "最大值"))
        self.checkBox_min.setText(_translate("Form", "最小值"))
        self.checkBox_sum.setText(_translate("Form", "总和"))
        self.checkBox_mean.setText(_translate("Form", "均值"))
        self.checkBox_median.setText(_translate("Form", "中位数"))
        self.checkBox_mode.setText(_translate("Form", "众数"))
        self.checkBox_sum_2.setText(_translate("Form", "峰度"))
        self.checkBox_sum_3.setText(_translate("Form", "偏度"))
        self.checkBox_var.setText(_translate("Form", "方差"))
        self.checkBox_std.setText(_translate("Form", "标准差"))
        self.checkBox_q1.setText(_translate("Form", "下四分位数Q1"))
        self.checkBox_q3.setText(_translate("Form", "上四分位数Q3"))
        self.checkBox_qrange.setText(_translate("Form", "四分位间距"))
        self.checkBox_cov.setText(_translate("Form", "变异系数"))
        self.checkBox_range.setText(_translate("Form", "极差"))
        self.checkBox_sum_4.setText(_translate("Form", "平方和"))
        self.checkBox_cov_2.setText(_translate("Form", "均值标准误"))
        self.pushButton_ok_2.setText(_translate("Form", "帮助"))
        self.pushButton_ok.setText(_translate("Form", "确定"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
