# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_woe.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_var = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_var.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_var.setObjectName("listWidget_var")
        self.verticalLayout_2.addWidget(self.listWidget_var)
        self.widget_3 = QtWidgets.QWidget(self.splitter)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_dependent_del = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_dependent_del.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_dependent_del.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pyqt/source/images/lc_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dependent_del.setIcon(icon)
        self.pushButton_dependent_del.setObjectName("pushButton_dependent_del")
        self.horizontalLayout_5.addWidget(self.pushButton_dependent_del)
        self.pushButton_dependent_add = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_dependent_add.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pyqt/source/images/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dependent_add.setIcon(icon1)
        self.pushButton_dependent_add.setObjectName("pushButton_dependent_add")
        self.horizontalLayout_5.addWidget(self.pushButton_dependent_add)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_dependent = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_dependent.setObjectName("listWidget_dependent")
        self.horizontalLayout_4.addWidget(self.listWidget_dependent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_independent_del = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_del.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_del.setText("")
        self.pushButton_independent_del.setIcon(icon)
        self.pushButton_independent_del.setObjectName("pushButton_independent_del")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_del)
        self.pushButton_independent_down = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_down.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pyqt/source/images/down1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_independent_down.setIcon(icon2)
        self.pushButton_independent_down.setObjectName("pushButton_independent_down")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_down)
        self.pushButton_independent_up = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_up.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_up.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pyqt/source/images/up1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_independent_up.setIcon(icon3)
        self.pushButton_independent_up.setObjectName("pushButton_independent_up")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_up)
        self.pushButton_independent_add = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_add.setText("")
        self.pushButton_independent_add.setIcon(icon1)
        self.pushButton_independent_add.setObjectName("pushButton_independent_add")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_add)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_independent = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_independent.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_independent.setObjectName("listWidget_independent")
        self.horizontalLayout_6.addWidget(self.listWidget_independent)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.formLayout = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout.setObjectName("formLayout")
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        self.label_24.setMinimumSize(QtCore.QSize(0, 22))
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_dataset_name = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_dataset_name.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_dataset_name.setText("")
        self.lineEdit_dataset_name.setObjectName("lineEdit_dataset_name")
        self.horizontalLayout_16.addWidget(self.lineEdit_dataset_name)
        self.pushButton_open = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_open.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout_16.addWidget(self.pushButton_open)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setMinimumSize(QtCore.QSize(0, 22))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.comboBox_criterion = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_criterion.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_criterion.setObjectName("comboBox_criterion")
        self.comboBox_criterion.addItem("")
        self.comboBox_criterion.addItem("")
        self.comboBox_criterion.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_criterion)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMinimumSize(QtCore.QSize(0, 22))
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 22))
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_6.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 22))
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setMinimumSize(QtCore.QSize(0, 22))
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_20.addWidget(self.spinBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 22))
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_6.setMaximum(999999999)
        self.spinBox_6.setProperty("value", 12345)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_11.addWidget(self.spinBox_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        self.label_25.setMinimumSize(QtCore.QSize(0, 22))
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_output_path = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_output_path.setObjectName("lineEdit_output_path")
        self.horizontalLayout_9.addWidget(self.lineEdit_output_path)
        self.toolButton_output_path = QtWidgets.QToolButton(self.widget_4)
        self.toolButton_output_path.setObjectName("toolButton_output_path")
        self.horizontalLayout_9.addWidget(self.toolButton_output_path)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.horizontalLayout_8.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_dataset = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_dataset.setObjectName("tableWidget_dataset")
        self.tableWidget_dataset.setColumnCount(0)
        self.tableWidget_dataset.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_dataset)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_code = QtWidgets.QPushButton(self.widget)
        self.pushButton_code.setObjectName("pushButton_code")
        self.horizontalLayout.addWidget(self.pushButton_code)
        self.pushButton_help = QtWidgets.QPushButton(self.widget)
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout.addWidget(self.pushButton_help)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton_back = QtWidgets.QPushButton(self.widget)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout.addWidget(self.pushButton_back)
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.pushButton_ok = QtWidgets.QPushButton(self.widget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计算WOE和IV"))
        self.label_2.setText(_translate("Form", "变量列表:"))
        self.label_3.setText(_translate("Form", "目标变量:"))
        self.pushButton_dependent_del.setProperty("level", _translate("Form", "tool"))
        self.pushButton_dependent_add.setProperty("level", _translate("Form", "tool"))
        self.label_5.setText(_translate("Form", "自变量:"))
        self.pushButton_independent_del.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_down.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_up.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_add.setProperty("level", _translate("Form", "tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "变量"))
        self.label_24.setText(_translate("Form", "数据集"))
        self.pushButton_open.setText(_translate("Form", "..."))
        self.label_8.setText(_translate("Form", "算法"))
        self.comboBox_criterion.setItemText(0, _translate("Form", "CART"))
        self.comboBox_criterion.setItemText(1, _translate("Form", "ID3"))
        self.comboBox_criterion.setItemText(2, _translate("Form", "C4.5"))
        self.label_13.setText(_translate("Form", "缺失值处理"))
        self.comboBox_4.setItemText(0, _translate("Form", "支持"))
        self.comboBox_4.setItemText(1, _translate("Form", "不支持"))
        self.label_15.setText(_translate("Form", "排序"))
        self.comboBox_6.setItemText(0, _translate("Form", "递增"))
        self.comboBox_6.setItemText(1, _translate("Form", "递减"))
        self.label_14.setText(_translate("Form", "可视化"))
        self.comboBox_5.setItemText(0, _translate("Form", "显示"))
        self.comboBox_5.setItemText(1, _translate("Form", "隐藏"))
        self.label_20.setText(_translate("Form", "最大分箱数"))
        self.label_12.setText(_translate("Form", "随机种子"))
        self.label_25.setText(_translate("Form", "输出路径"))
        self.toolButton_output_path.setText(_translate("Form", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "选项"))
        self.pushButton_code.setText(_translate("Form", "代码"))
        self.pushButton_help.setText(_translate("Form", "帮助"))
        self.pushButton_back.setText(_translate("Form", "上一步"))
        self.pushButton_next.setText(_translate("Form", "下一步"))
        self.pushButton_ok.setText(_translate("Form", "完成"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
import pyqtsource_rc
