# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .widgets import PMTableWidget, PMFlowWidget, PMReportWidget, PMTextEditConsole, PMPageData, PMPageStats, \
    PMPagePlot, PMPageModel, PMPage, PMMenuBar, PMToolBarTop, PMToolBarRight, PMFilesTreeview, PMDatasetsTreeview, \
    PMStatusBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_left = QtWidgets.QWidget(self.splitter_3)
        self.widget_left.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget_left)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget_storehouse = PMDatasetsTreeview(self.splitter)

        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7"
                                            )
        self.tabWidget_files = QtWidgets.QTabWidget(self.widget_4)
        self.tabWidget_files.setObjectName("tabWidget_2")

        self.tabWidget_files.setCurrentIndex(0)

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.treeView_files = PMFilesTreeview()  # QtWidgets.QTreeView(self.tab)

        self.verticalLayout_8.addWidget(self.treeView_files)

        self.tabWidget_files.addTab(self.tab, "")

        self.tabWidget_files.setTabText(self.tabWidget_files.indexOf(self.tab), _translate("MainWindow", "文件"))

        self.verticalLayout_7.addWidget(self.tabWidget_files)
        self.verticalLayout_3.addWidget(self.splitter)
        self.widget = QtWidgets.QWidget(self.splitter_3)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_data = QtWidgets.QWidget()
        self.tab_data.setObjectName("tab_data")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_data)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.tableWidget_dataset = PMTableWidget()

        self.horizontalLayout_2.addWidget(self.tableWidget_dataset)

        self.tabWidget.addTab(self.tab_data, "")

        self.tab_flow = PMFlowWidget()

        self.tabWidget.addTab(self.tab_flow, "")

        self.tab_report = PMReportWidget()
        self.tabWidget.addTab(self.tab_report, "")

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_data), _translate("MainWindow", "数据"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_flow), _translate("MainWindow", "流程"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_report), _translate("MainWindow", "输出"))

        self.tabWidget_console = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_console.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_console.setObjectName("tabWidget_console")

        self.text_edit_console_tab = PMTextEditConsole()

        self.tabWidget_console.addTab(self.text_edit_console_tab, "")

        self.tab_4 = PMTextEditConsole()
        self.textEdit_console_2 = self.tab_4.textEdit_console

        self.tabWidget_console.addTab(self.tab_4, "")

        self.tabWidget_console.setCurrentIndex(1)
        self.tabWidget_console.setTabText(self.tabWidget_console.indexOf(self.text_edit_console_tab),
                                          _translate("MainWindow", "日志"))
        self.tabWidget_console.setTabText(self.tabWidget_console.indexOf(self.tab_4), _translate("MainWindow", "控制台"))

        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout.addWidget(self.splitter_3)

        self.widget_right = QtWidgets.QWidget(self.centralwidget)
        self.widget_right.setMinimumSize(QtCore.QSize(280, 0))
        self.widget_right.setMaximumSize(QtCore.QSize(280, 16777215))
        self.widget_right.setObjectName("widget_right")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_right)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_right)
        self.stackedWidget.setMinimumSize(QtCore.QSize(270, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_assess = PMPage(self)
        self.page_data = PMPageData(self)
        self.page_stats = PMPageStats(self)
        self.page_plot = PMPagePlot(self)
        self.page_model = PMPageModel(self)  # QtWidgets.QWidget()
        self.stackedWidget.addWidget(self.page_data)
        self.stackedWidget.addWidget(self.page_stats)
        self.stackedWidget.addWidget(self.page_plot)
        self.stackedWidget.addWidget(self.page_model)
        self.stackedWidget.addWidget(self.page_assess)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget_right)

        self.menubar = PMMenuBar(self)
        MainWindow.setMenuBar(self.menubar)
        # MainWindow.setMenuBar()

        self.statusBar = PMStatusBar(self)

        MainWindow.setStatusBar(self.statusBar)

        self.toolBar_left = PMToolBarTop(MainWindow)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_left)

        self.toolBar_right = PMToolBarRight(MainWindow)
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar_right)

        self.tabWidget.setCurrentIndex(0)

        self.stackedWidget.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setWindowTitle(_translate("MainWindow", "PyMiner"))

        MainWindow.setCentralWidget(self.centralwidget)
        self.bind_events()

    def bind_events(self):
        self.action_quit.triggered.connect(self.close)


import pyqtsource_rc
