# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_tree.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_var = QtWidgets.QListWidget(self.widget_2)
        self.listWidget_var.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_var.setObjectName("listWidget_var")
        self.verticalLayout_2.addWidget(self.listWidget_var)
        self.widget_3 = QtWidgets.QWidget(self.splitter)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_dependent_del = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_dependent_del.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_dependent_del.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pyqt/source/images/lc_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dependent_del.setIcon(icon)
        self.pushButton_dependent_del.setObjectName("pushButton_dependent_del")
        self.horizontalLayout_5.addWidget(self.pushButton_dependent_del)
        self.pushButton_dependent_add = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_dependent_add.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pyqt/source/images/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dependent_add.setIcon(icon1)
        self.pushButton_dependent_add.setObjectName("pushButton_dependent_add")
        self.horizontalLayout_5.addWidget(self.pushButton_dependent_add)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_dependent = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_dependent.setObjectName("listWidget_dependent")
        self.horizontalLayout_4.addWidget(self.listWidget_dependent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_independent_del = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_del.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_del.setText("")
        self.pushButton_independent_del.setIcon(icon)
        self.pushButton_independent_del.setObjectName("pushButton_independent_del")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_del)
        self.pushButton_independent_down = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_down.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_down.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pyqt/source/images/down1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_independent_down.setIcon(icon2)
        self.pushButton_independent_down.setObjectName("pushButton_independent_down")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_down)
        self.pushButton_independent_up = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_up.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_independent_up.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pyqt/source/images/up1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_independent_up.setIcon(icon3)
        self.pushButton_independent_up.setObjectName("pushButton_independent_up")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_up)
        self.pushButton_independent_add = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_independent_add.setText("")
        self.pushButton_independent_add.setIcon(icon1)
        self.pushButton_independent_add.setObjectName("pushButton_independent_add")
        self.horizontalLayout_7.addWidget(self.pushButton_independent_add)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_independent = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_independent.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_independent.setObjectName("listWidget_independent")
        self.horizontalLayout_6.addWidget(self.listWidget_independent)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_4.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.formLayout = QtWidgets.QFormLayout(self.widget_4)
        self.formLayout.setObjectName("formLayout")
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        self.label_24.setMinimumSize(QtCore.QSize(0, 22))
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_dataset_name = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_dataset_name.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_dataset_name.setText("")
        self.lineEdit_dataset_name.setObjectName("lineEdit_dataset_name")
        self.horizontalLayout_16.addWidget(self.lineEdit_dataset_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setMinimumSize(QtCore.QSize(0, 22))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.comboBox_criterion = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_criterion.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_criterion.setObjectName("comboBox_criterion")
        self.comboBox_criterion.addItem("")
        self.comboBox_criterion.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_criterion)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMinimumSize(QtCore.QSize(0, 22))
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 22))
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 22))
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setMinimumSize(QtCore.QSize(0, 22))
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comboBox_11 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_11.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_11)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setMinimumSize(QtCore.QSize(0, 22))
        self.label_9.setToolTip("")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.spinBox = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_15.addWidget(self.spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setMinimumSize(QtCore.QSize(0, 22))
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.spinBox_max_depth = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_max_depth.setMaximum(20)
        self.spinBox_max_depth.setProperty("value", 6)
        self.spinBox_max_depth.setObjectName("spinBox_max_depth")
        self.horizontalLayout_14.addWidget(self.spinBox_max_depth)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setMinimumSize(QtCore.QSize(0, 22))
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.spinBox_min_samples_split = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_min_samples_split.setMaximum(200)
        self.spinBox_min_samples_split.setProperty("value", 100)
        self.spinBox_min_samples_split.setObjectName("spinBox_min_samples_split")
        self.horizontalLayout_13.addWidget(self.spinBox_min_samples_split)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setMinimumSize(QtCore.QSize(0, 22))
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.spinBox_min_samples_leaf = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_min_samples_leaf.setProperty("value", 50)
        self.spinBox_min_samples_leaf.setObjectName("spinBox_min_samples_leaf")
        self.horizontalLayout_12.addWidget(self.spinBox_min_samples_leaf)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 22))
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_6.setMaximum(999999999)
        self.spinBox_6.setProperty("value", 12345)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_11.addWidget(self.spinBox_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setMinimumSize(QtCore.QSize(0, 22))
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.comboBox_12 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_12.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_12)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.formLayout.setLayout(13, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        self.label_25.setMinimumSize(QtCore.QSize(0, 22))
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_result_path = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_result_path.setObjectName("lineEdit_result_path")
        self.horizontalLayout_9.addWidget(self.lineEdit_result_path)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget_4)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_9.addWidget(self.toolButton_2)
        self.formLayout.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_6.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBox_6)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem13)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setMinimumSize(QtCore.QSize(0, 22))
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.doubleSpinBox_train_size = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.doubleSpinBox_train_size.setMaximum(1.0)
        self.doubleSpinBox_train_size.setSingleStep(0.1)
        self.doubleSpinBox_train_size.setProperty("value", 0.7)
        self.doubleSpinBox_train_size.setObjectName("doubleSpinBox_train_size")
        self.horizontalLayout_22.addWidget(self.doubleSpinBox_train_size)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem14)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_22)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.FieldRole, spacerItem15)
        self.horizontalLayout_8.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_3)
        self.widget_5.setObjectName("widget_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setMinimumSize(QtCore.QSize(0, 22))
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lineEdit_dataset_name_4 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_dataset_name_4.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_dataset_name_4.setText("")
        self.lineEdit_dataset_name_4.setObjectName("lineEdit_dataset_name_4")
        self.horizontalLayout_25.addWidget(self.lineEdit_dataset_name_4)
        self.toolButton = QtWidgets.QToolButton(self.widget_5)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_25.addWidget(self.toolButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem16)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_25)
        self.label_26 = QtWidgets.QLabel(self.widget_5)
        self.label_26.setMinimumSize(QtCore.QSize(0, 22))
        self.label_26.setObjectName("label_26")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.comboBox = QtWidgets.QComboBox(self.widget_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_23.addWidget(self.comboBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_23)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setMinimumSize(QtCore.QSize(0, 22))
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_24.addWidget(self.comboBox_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_24)
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        self.label_17.setMinimumSize(QtCore.QSize(0, 22))
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_5.setMaximum(10)
        self.spinBox_5.setProperty("value", 2)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_27.addWidget(self.spinBox_5)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem19)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_27)
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setMinimumSize(QtCore.QSize(0, 22))
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_27 = QtWidgets.QLabel(self.widget_5)
        self.label_27.setMinimumSize(QtCore.QSize(0, 22))
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lineEdit_dataset_name_6 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_dataset_name_6.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_dataset_name_6.setText("")
        self.lineEdit_dataset_name_6.setObjectName("lineEdit_dataset_name_6")
        self.horizontalLayout_28.addWidget(self.lineEdit_dataset_name_6)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget_5)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_28.addWidget(self.toolButton_4)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem20)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lineEdit_dataset_name_7 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_dataset_name_7.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit_dataset_name_7.setText("")
        self.lineEdit_dataset_name_7.setObjectName("lineEdit_dataset_name_7")
        self.horizontalLayout_29.addWidget(self.lineEdit_dataset_name_7)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget_5)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_29.addWidget(self.toolButton_5)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem21)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_29)
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setMinimumSize(QtCore.QSize(0, 22))
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_30.addWidget(self.comboBox_3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem22)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_30)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_code = QtWidgets.QPushButton(self.widget)
        self.pushButton_code.setObjectName("pushButton_code")
        self.horizontalLayout.addWidget(self.pushButton_code)
        self.pushButton_help = QtWidgets.QPushButton(self.widget)
        self.pushButton_help.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pyqt/source/images/lc_helpindex.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_help.setIcon(icon4)
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout.addWidget(self.pushButton_help)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem23)
        self.pushButton_ok = QtWidgets.QPushButton(self.widget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "决策树"))
        self.label_2.setText(_translate("Form", "变量列表:"))
        self.label_3.setText(_translate("Form", "目标变量:"))
        self.pushButton_dependent_del.setProperty("level", _translate("Form", "tool"))
        self.pushButton_dependent_add.setProperty("level", _translate("Form", "tool"))
        self.label_5.setText(_translate("Form", "自变量:"))
        self.pushButton_independent_del.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_down.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_up.setProperty("level", _translate("Form", "tool"))
        self.pushButton_independent_add.setProperty("level", _translate("Form", "tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "变量"))
        self.label_24.setText(_translate("Form", "数据集"))
        self.label_8.setText(_translate("Form", "特征选择准则"))
        self.comboBox_criterion.setItemText(0, _translate("Form", "Gini"))
        self.comboBox_criterion.setItemText(1, _translate("Form", "Entropy"))
        self.label_13.setText(_translate("Form", "算法"))
        self.comboBox_4.setItemText(0, _translate("Form", "CART"))
        self.comboBox_4.setItemText(1, _translate("Form", "ID3"))
        self.comboBox_4.setItemText(2, _translate("Form", "C4.5"))
        self.label_15.setText(_translate("Form", "支持模型"))
        self.label_14.setText(_translate("Form", "树结构"))
        self.comboBox_5.setItemText(0, _translate("Form", "二叉树"))
        self.comboBox_5.setItemText(1, _translate("Form", "多叉树"))
        self.label_20.setText(_translate("Form", "特征属性多次使用"))
        self.comboBox_11.setItemText(0, _translate("Form", "支持"))
        self.comboBox_11.setItemText(1, _translate("Form", "不支持"))
        self.comboBox_11.setItemText(2, _translate("Form", "不支持"))
        self.label_9.setText(_translate("Form", "最大分支"))
        self.label_10.setText(_translate("Form", "最大深度"))
        self.label_22.setText(_translate("Form", "最小父节点"))
        self.spinBox_min_samples_split.setToolTip(_translate("Form", "设置结点的最小样本数量，当样本数量可能小于此值时，结点将不会在划分。"))
        self.label_23.setText(_translate("Form", "最小子节点"))
        self.label_12.setText(_translate("Form", "随机种子"))
        self.label_21.setText(_translate("Form", "剪枝策略"))
        self.comboBox_12.setItemText(0, _translate("Form", "预剪枝"))
        self.comboBox_12.setItemText(1, _translate("Form", "后剪枝"))
        self.label_25.setText(_translate("Form", "输出路径"))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.comboBox_6.setItemText(0, _translate("Form", "分类、回归"))
        self.comboBox_6.setItemText(1, _translate("Form", "分类"))
        self.label_16.setText(_translate("Form", "训练集大小"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "选项"))
        self.label_18.setText(_translate("Form", "输出文件路径:"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label_26.setText(_translate("Form", "是否填充颜色:"))
        self.comboBox.setItemText(0, _translate("Form", "是"))
        self.comboBox.setItemText(1, _translate("Form", "否"))
        self.label_11.setText(_translate("Form", "是否圆角矩形:"))
        self.comboBox_2.setItemText(0, _translate("Form", "是"))
        self.comboBox_2.setItemText(1, _translate("Form", "否"))
        self.label_17.setText(_translate("Form", "数据精度:"))
        self.label_19.setText(_translate("Form", "特征名称:"))
        self.label_27.setText(_translate("Form", "分类名称:"))
        self.toolButton_4.setText(_translate("Form", "..."))
        self.toolButton_5.setText(_translate("Form", "..."))
        self.label_28.setText(_translate("Form", "方向:"))
        self.comboBox_3.setItemText(0, _translate("Form", "从上到下"))
        self.comboBox_3.setItemText(1, _translate("Form", "从左到右"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "图形"))
        self.pushButton_code.setText(_translate("Form", "代码"))
        self.pushButton_ok.setText(_translate("Form", "确定"))
        self.pushButton_cancel.setText(_translate("Form", "取消"))
import pyqtsource_rc
